{{- if and .Values.externalMariadb.enabled (not .Values.externalMariadb.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lighthouse-ci.mariadb.secretName" . }}
  labels:
    {{- include "lighthouse-ci.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-password: {{ .Values.externalMariadb.password | b64enc | quote }}
{{- end }}
