{{- if (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lighthouse-ci.secretName" . }}
  labels:
    {{- include "lighthouse-ci.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.basicAuthUsername .Values.basicAuthPassword }}
  basic-auth-password: {{ .Values.basicAuthPassword | b64enc | quote }}
  {{- end }}
{{- end }}
