{{- if .Values.updater.pdb.create }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vertical-pod-autoscaler.updater.fullname" . }}
  labels:
    {{- include "vertical-pod-autoscaler.updater.labels" . | nindent 4 }}
spec:
  {{- if .Values.updater.pdb.minAvailable }}
  minAvailable: {{ .Values.updater.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.updater.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.updater.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vertical-pod-autoscaler.updater.selectorLabels" . | nindent 6 }}
{{- end }}
